name: Self-tests for scanners

on:
  push:
  pull_request:

jobs:
  man-db:
    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-22.04, ubuntu-24.04]
    runs-on: ${{ matrix.os }}
    steps:
      - run: |
          sudo apt-get update

          # start another disk-heavy job
          sudo snap install --no-wait trivy

          timeout 30s sudo apt-get --yes install sl

          date
